<?php
declare(strict_types=1);

// Seed data imported from the Bean and Bear recipe book (Edition 5).
// Used once, by db.php, to populate an empty recipes table.
return [
    [
        'flavour_key' => 'dark-chocolate',
        'sort_order' => 1,
        'name' => 'Dark Chocolate',
        'tagline' => 'The chocolate that changed chocolate.',
        'story' => 'I never really liked Easter eggs. They always seemed to taste of… not very much. Then I tried proper 80% dark chocolate and it completely changed what I thought chocolate could be. This is the gelato version of that moment: dark, intense and unapologetically chocolatey.',
        'brief' => 'Deep, adult and unmistakably chocolate-led: high cocoa intensity, restrained sweetness and a clean finish.',
        'ingredients' => [
            ['group' => null, 'qty' => '300ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '15g', 'item' => 'Light brown sugar'],
            ['group' => null, 'qty' => '150ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '3', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '100g', 'item' => '80% dark chocolate with sea salt'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '30g', 'item' => 'Cocoa powder'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Espresso powder'],
            ['group' => null, 'qty' => '90g', 'item' => 'Caster sugar'],
        ],
        'method' => [
            'Combine milk and cream and heat until steaming.',
            'Whisk yolks with both sugars, cocoa and espresso powder.',
            'Temper the yolks with the hot dairy, return to the pan and cook gently to 82–84°C.',
            'Pour over the dark chocolate and blend until glossy and completely emulsified.',
            'Add vanilla, chill rapidly, then mature covered in the refrigerator overnight.',
            'Freeze/churn using the current Bean & Bear production method; record finished batch weight and texture.',
        ],
    ],
    [
        'flavour_key' => 'vanilla',
        'sort_order' => 2,
        'name' => 'Vanilla',
        'tagline' => 'Or, as my girls call it, ’nilla’.',
        'story' => 'Nothing beats a Mr Whippy in the park after pushing the girls on the swings. It isn’t complicated or sophisticated. It’s just one of those little moments that makes you happy. Vanilla ice cream will always remind me of that.',
        'brief' => 'Simple only in appearance: creamy, fragrant Madagascan vanilla with enough richness to feel luxurious but never heavy.',
        'ingredients' => [
            ['group' => null, 'qty' => '440g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '1', 'item' => 'Vanilla pod'],
            ['group' => null, 'qty' => '100g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Vanilla bean paste'],
            ['group' => null, 'qty' => '95g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '2', 'item' => 'Egg yolks'],
        ],
        'method' => [
            'Split the vanilla pod and scrape the seeds into the milk and cream; add the pod.',
            'Heat until steaming, cover and infuse for 20 minutes. Remove the pod and allow the dairy to cool slightly.',
            'Whisk yolks and sugar. Temper with the dairy, return to the pan and cook gently to 82–84°C.',
            'Add vanilla bean paste and salt.',
            'Chill rapidly and mature overnight.',
            'Freeze/churn; record finished weight and serving behaviour.',
        ],
    ],
    [
        'flavour_key' => 'wild-strawberry',
        'sort_order' => 3,
        'name' => 'Wild Strawberry & Lemon',
        'tagline' => 'Pick one. Eat two.',
        'story' => 'Every year we go strawberry picking as a family. In theory, anyway. Mum and Dad do most of the picking while the children eat their way through the field. Then comes the awkward bit at the till, pretending we have no idea where all those red smudges around their mouths came from.',
        'brief' => 'Fresh strawberry first, lifted by lemon zest and a touch of Sicilian lemon extract; bright, summery and recognisably fruit-led.',
        'ingredients' => [
            ['group' => null, 'qty' => '225g', 'item' => 'Ripe strawberries'],
            ['group' => null, 'qty' => '20g', 'item' => 'Caster sugar for fruit'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '8g', 'item' => 'Freeze-dried strawberries, blended into the base'],
            ['group' => null, 'qty' => '180ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '60ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '50g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '0.4g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '', 'item' => 'Zest of 1 lemon'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Sicilian lemon extract'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '4g', 'item' => 'Freeze-dried strawberries, crushed, to finish'],
        ],
        'method' => [
            'Roast about 125g of the strawberries with the 20g sugar until concentrated; cool.',
            'Blend roasted and fresh strawberries with lemon juice and the 8g freeze-dried strawberries.',
            'Heat milk and cream with lemon zest; infuse covered for 10 minutes, then strain.',
            'Whisk in caster sugar, milk powder, xanthan and Sicilian lemon extract and heat to about 82°C; chill completely.',
            'Blend in strawberry mixture and salt; mature cold and freeze/churn.',
            'Finish with the 4g crushed freeze-dried strawberry.',
        ],
    ],
    [
        'flavour_key' => 'tiramisu',
        'sort_order' => 4,
        'name' => 'Tiramisu',
        'tagline' => 'My first proper Italian dessert.',
        'story' => 'Tiramisu was the first dessert I ever ordered in an Italian restaurant. Coffee, mascarpone, cocoa – I’d never had anything quite like it. There still isn’t anything quite like it. So ours doesn’t try to reinvent it. It just tries to do it justice.',
        'brief' => 'Coffee, mascarpone and cocoa in balance. It should taste like tiramisu, not merely coffee ice cream.',
        'ingredients' => [
            ['group' => null, 'qty' => '250ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '160ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '60ml', 'item' => 'Strong espresso'],
            ['group' => null, 'qty' => '150g', 'item' => 'Mascarpone'],
            ['group' => null, 'qty' => '1', 'item' => 'Shot espresso martini mix'],
            ['group' => null, 'qty' => '4', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Cocoa powder'],
            ['group' => null, 'qty' => '90g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => 'optional', 'item' => 'Ladyfinger crumb and shaved'],
            ['group' => null, 'qty' => '', 'item' => 'chocolate'],
            ['group' => null, 'qty' => '2 tsp', 'item' => 'Vanilla extract'],
        ],
        'method' => [
            'Heat milk and cream until steaming.',
            'Whisk yolks, sugar and cocoa; temper with the dairy and cook to 82–84°C.',
            'Cool to about 55°C, then blend in mascarpone until smooth.',
            'Add espresso, espresso martini mix, vanilla and salt.',
            'Chill rapidly and mature overnight.',
            'Freeze/churn. Add optional ladyfinger crumb or chocolate only after the base is frozen.',
        ],
    ],
    [
        'flavour_key' => 'lemon-meringue-pie',
        'sort_order' => 5,
        'name' => 'Lemon Meringue Pie',
        'tagline' => 'My wife’s favourite dessert.',
        'story' => 'I once made her a lemon meringue pie and dropped the entire thing while taking it out of the oven. I ate it off the floor with a spoon. I have no regrets.',
        'brief' => 'Creamy lemon-pie character with real acidity and sweet meringue contrast; indulgent without becoming cloying.',
        'ingredients' => [
            ['group' => null, 'qty' => '220ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '100ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '70g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '10g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '0.4g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '', 'item' => 'Zest of 2 lemons'],
            ['group' => null, 'qty' => '55ml', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => '3', 'item' => 'Egg yolks — verify against original'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '', 'item' => 'Meringue crumble and freeze-dried raspberry, to finish'],
        ],
        'method' => [
            'Infuse milk and cream with lemon zest until steaming; rest 10 minutes.',
            'Combine sugar, milk powder and xanthan. If using the recorded yolks, whisk them into the sugar mixture.',
            'Temper and cook the base gently to approximately 82°C.',
            'Chill completely before blending in lemon juice, vanilla and salt.',
            'Mature cold and freeze/churn.',
            'Finish with meringue crumble and freeze-dried raspberry at service.',
        ],
    ],
    [
        'flavour_key' => 'raspberry-pavlova',
        'sort_order' => 6,
        'name' => 'Raspberry Pavlova',
        'tagline' => 'Nina’s favourite.',
        'story' => 'If I were on Desert Island Discs, raspberries would be the one thing I’d take with me. Although, come to think of it, I don’t think you’re allowed to take food. Either way, I’m taking raspberries. And Nina would approve.',
        'brief' => 'Sharp raspberry, creamy base and crisp-sweet meringue contrast. Raspberry must remain the star.',
        'ingredients' => [
            ['group' => null, 'qty' => '150g', 'item' => 'Raspberries'],
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '65g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => '0.4g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '', 'item' => 'Meringue, to finish'],
        ],
        'method' => [
            'Blend raspberries with lemon juice and pass through a sieve if a seedless finish is required.',
            'Combine sugar, milk powder and xanthan.',
            'Heat milk and cream; whisk in dry ingredients and heat to about 82°C.',
            'Chill completely, then blend in raspberry purée, vanilla and salt to taste.',
            'Mature cold and freeze/churn.',
            'Finish with crushed meringue at service so it remains crisp.',
        ],
    ],
    [
        'flavour_key' => 'key-lime-pie',
        'sort_order' => 7,
        'name' => 'Key Lime Pie',
        'tagline' => 'Florida sunshine in a scoop.',
        'story' => 'Florida sun. Disney World. Mickey Mouse. American diners. Key lime pie. Bliss. This is our little taste of Florida, without the nine-hour flight.',
        'brief' => 'Tangy lime, creamy pie filling and biscuit/meringue cues; bright enough to cut through the dairy.',
        'ingredients' => [
            ['group' => null, 'qty' => '180g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '100g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '90g', 'item' => 'Condensed milk'],
            ['group' => null, 'qty' => '20g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '', 'item' => 'Zest of 2 limes'],
            ['group' => null, 'qty' => '25g', 'item' => 'Lime juice'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '', 'item' => '35–40g lime curd'],
            ['group' => null, 'qty' => '', 'item' => 'Shortbread crumb, to finish'],
        ],
        'method' => [
            'Heat milk, cream, condensed milk, sugar, milk powder and lime zest to about 82°C.',
            'Remove from heat and chill completely.',
            'Blend in lime curd, lime juice and salt once cold.',
            'Mature in the refrigerator.',
            'Freeze/churn.',
            'Finish with shortbread crumb at service.',
        ],
    ],
    [
        'flavour_key' => 'banoffee-pie',
        'sort_order' => 8,
        'name' => 'Banoffee Pie',
        'tagline' => 'Born around a campfire.',
        'story' => 'We used to camp in France. After the barbecue, we’d take old bananas, stuff them with bits of Snickers, wrap them in foil and bury them in the embers. Ten minutes later you’d be scraping warm, gooey, caramel-chocolate banana from the skin with a spoon. This is the slightly more civilised version.',
        'brief' => 'Roasted banana, caramel depth and biscuit warmth. Generous and nostalgic rather than simply sugary.',
        'ingredients' => [
            ['group' => null, 'qty' => '140g', 'item' => 'Ripe banana'],
            ['group' => null, 'qty' => '150g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '70g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '65g', 'item' => 'Dulce de leche'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '10g', 'item' => 'Light brown sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '5g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '', 'item' => 'Biscuit crumb or dulce de leche, to finish'],
        ],
        'method' => [
            'Roast banana with brown sugar at 190°C fan for about 20 minutes; cool.',
            'Heat milk and cream with dulce de leche and milk powder to about 82°C.',
            'Chill slightly, then blend in roasted banana, vanilla, lemon juice and salt.',
            'Chill rapidly and mature overnight.',
            'Freeze/churn.',
            'Finish with biscuit crumb or a restrained dulce de leche drizzle.',
        ],
    ],
    [
        'flavour_key' => 'black-forest',
        'sort_order' => 9,
        'name' => 'Black Forest',
        'tagline' => 'The Christmas pudding of champions.',
        'story' => 'It reminds me of pulling a frozen Black Forest gateau from the freezer at Christmas, waiting approximately a billion hours for it to defrost, then demolishing it as though nobody had fed us for a week. Cherry. Chocolate. Christmas. Magnificent.',
        'brief' => 'Dark chocolate and sour cherry with a grown-up bitterness; rich, festive and clearly Black Forest.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '100ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '3', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '60g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '70g', 'item' => '80% dark chocolate'],
            ['group' => null, 'qty' => '12g', 'item' => 'Cocoa'],
            ['group' => null, 'qty' => '10g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '240g', 'item' => 'Sour cherries'],
            ['group' => null, 'qty' => '20g', 'item' => 'Caster sugar for cherries'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '10ml', 'item' => 'Monin cherry syrup'],
            ['group' => null, 'qty' => '', 'item' => 'Dark chocolate shavings, to finish'],
        ],
        'method' => [
            'Cook cherries with 20g sugar until softened and concentrated; add lemon juice and a splash of Monin cherry syrup to deepen the flavour, then cool.',
            'Heat milk and cream. Whisk yolks with sugar, cocoa, milk powder and xanthan.',
            'Temper, return to the pan and cook to 82–84°C.',
            'Pour over dark chocolate, blend smooth, add salt and chill rapidly.',
            'Blend or fold the cold cherry preparation into the base according to the desired final texture; record the chosen method.',
            'Freeze/churn and finish with dark chocolate shavings.',
        ],
    ],
    [
        'flavour_key' => 'salted-caramel',
        'sort_order' => 10,
        'name' => 'Salted Caramel',
        'tagline' => 'Mum’s favourite.',
        'story' => 'Slightly burnt. Ever so sweet. Buttery. Salty. Some flavours belong to summer. Some belong to winter. Salted caramel somehow belongs to both. Mum would choose this one.',
        'brief' => 'Caramel taken just far enough for bitterness, then balanced with butter, salt and shortbread.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '100ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '3', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '130g', 'item' => 'Caster sugar total — allocation to verify'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '40g', 'item' => 'Butter'],
            ['group' => null, 'qty' => '', 'item' => 'Brown-butter shortbread, to finish'],
        ],
        'method' => [
            'Caramelise the designated caramel sugar to a deep amber; carefully incorporate warm dairy and butter.',
            'Whisk remaining sugar with yolks, milk powder and xanthan.',
            'Temper with the caramel dairy and cook gently to 82–84°C.',
            'Add vanilla and salt, chill rapidly and mature overnight.',
            'Freeze/churn. Taste specifically for caramel intensity; original development note says to double the caramel.',
            'Finish with brown-butter shortbread at service. S A LT E D C A R A M E L · M E T H O D                                                                               24',
        ],
    ],
    [
        'flavour_key' => 'kulfi',
        'sort_order' => 11,
        'name' => 'Kulfi',
        'tagline' => 'For Mum and Dad.',
        'story' => 'My mum and dad loved travelling around India, searching for wonderful flora and fauna before relaxing at the end of the day with a mango lassi. Mango, saffron and cardamom. This is my little homage to their happiness in those moments.',
        'brief' => 'Mango supported by saffron and cardamom; aromatic and rounded, with spice present but never perfumed.',
        'ingredients' => [
            ['group' => null, 'qty' => '180g', 'item' => 'Mango pulp'],
            ['group' => null, 'qty' => '8', 'item' => 'Saffron strands'],
            ['group' => null, 'qty' => '140g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '3', 'item' => 'Green cardamom pods, crushed'],
            ['group' => null, 'qty' => '70g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '5g', 'item' => 'Lime juice'],
            ['group' => null, 'qty' => '65g', 'item' => 'Condensed milk'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
        ],
        'method' => [
            'Heat milk and cream with saffron and cardamom; cover and infuse for 15 minutes.',
            'Strain, then whisk in condensed milk and milk powder and heat to about 82°C.',
            'Chill completely.',
            'Blend in mango pulp, lime juice and salt.',
            'Mature cold and freeze/churn.',
            'Taste after freezing and adjust spice only in the next recorded version.',
        ],
    ],
    [
        'flavour_key' => 'roasted-pineapple',
        'sort_order' => 12,
        'name' => 'Roasted Pineapple',
        'tagline' => 'No worries. No problems.',
        'story' => 'This one tastes like holidays. Sitting beside a pool with a pina colada and absolutely nothing to worry about. Except perhaps how quickly the drink seems to be disappearing. Pineapple, coconut and lime. Holiday mode activated.',
        'brief' => 'Roasted pineapple sweetness with coconut and lime freshness; holiday flavour without becoming cocktail syrup.',
        'ingredients' => [
            ['group' => null, 'qty' => '200g', 'item' => 'Pineapple'],
            ['group' => null, 'qty' => '15g', 'item' => 'Light brown sugar'],
            ['group' => null, 'qty' => '200g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '50g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '25g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '10g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '5g', 'item' => 'Monin coconut syrup'],
            ['group' => null, 'qty' => '20g', 'item' => 'Lime juice'],
            ['group' => null, 'qty' => '16g', 'item' => 'Dark rum'],
            ['group' => null, 'qty' => '', 'item' => 'Lime zest'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
        ],
        'method' => [
            'Roast pineapple with brown sugar at 200°C fan for about 25 minutes; cool and purée, then sieve.',
            'Heat whole milk and cream with caster sugar, glucose and milk powder to about 82°C.',
            'Off the heat, stir in the Monin coconut syrup. Chill completely.',
            'Blend in pineapple purée, lime juice, rum, zest and salt.',
            'Mature cold and freeze/churn.',
            'Rum and lime are doubled against the first trial, which were being lost in the creamy texture — this is now the confirmed ratio.',
        ],
    ],
    [
        'flavour_key' => 'peach-melba',
        'sort_order' => 13,
        'name' => 'Peach Melba',
        'tagline' => 'The peach without the problem.',
        'story' => 'Meg is afraid of peaches. Not the taste. The fur. She thinks it’s deeply weird that a fruit should be furry, and when you think about it, she may have a point. So this is our attempt at eating peaches without having to deal with the fur.',
        'brief' => 'Soft ripe peach with raspberry acidity; elegant fruit flavour and a clean finish.',
        'ingredients' => [
            ['group' => null, 'qty' => '180g', 'item' => 'Peaches'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '80g', 'item' => 'Raspberries'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '130g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '8g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '65g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
        ],
        'method' => [
            'Purée peaches and raspberries with lemon juice; sieve if desired.',
            'Heat milk and cream with sugar, glucose and milk powder to about 82°C.',
            'Chill completely.',
            'Blend in fruit purée, vanilla and salt.',
            'Mature cold and freeze/churn.',
            'Record colour, fruit intensity and melt before adjusting sugar or fruit.',
        ],
    ],
    [
        'flavour_key' => 'liquorice-blackcurrant',
        'sort_order' => 14,
        'name' => 'Liquorice & Blackcurrant',
        'tagline' => 'One each. That’s your lot.',
        'story' => 'On long car journeys, Mum always kept a packet of liquorice and blackcurrant sweets in the glove compartment. If my sister and I managed not to tear each other’s eyes out, we could have one. We only ever got one.',
        'brief' => 'Dark liquorice against tart blackcurrant. Distinctive, nostalgic and deliberately not too sweet.',
        'ingredients' => [
            ['group' => null, 'qty' => '150g', 'item' => 'Blackcurrants'],
            ['group' => null, 'qty' => '20g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '180g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '4g', 'item' => 'Liquorice powder'],
            ['group' => null, 'qty' => '80g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '8g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '25g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
        ],
        'method' => [
            'Cook blackcurrants briefly until they burst; blend and sieve.',
            'Heat milk and cream with sugar, glucose, milk powder and liquorice powder to about 82°C.',
            'Chill completely.',
            'Blend in blackcurrant purée, vanilla, lemon and salt.',
            'Mature cold and freeze/churn.',
            'Assess liquorice after freezing before increasing it; it should support rather than dominate.',
        ],
    ],
    [
        'flavour_key' => 'passionfruit',
        'sort_order' => 15,
        'name' => 'Passionfruit',
        'tagline' => 'Orla thinks they look like bogies.',
        'story' => 'She isn’t wrong. And she’d know. She’s eaten a lot of bogies. Personally, I prefer passionfruit. It’s my favourite. So this one has more passionfruit than you can shake a stick at: sharp, smooth, ridiculously moreish and considerably better than bogies.',
        'brief' => 'An unapologetically intense passionfruit flavour: sharp, aromatic, smooth and refreshing.',
        'ingredients' => [
            ['group' => null, 'qty' => '', 'item' => 'Pulp of 10 passionfruits'],
            ['group' => null, 'qty' => '150ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '65g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '0.5g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '', 'item' => 'Popping candy, to finish'],
        ],
        'method' => [
            'Sieve the passionfruit pulp, retaining the juice and a small quantity of seeds if desired.',
            'Whisk sugar, milk powder and xanthan together.',
            'Heat milk and cream; whisk in the dry ingredients and heat to about 82°C.',
            'Chill the dairy base completely before blending in the passionfruit and salt.',
            'Mature cold, then freeze/churn.',
            'Finish each serving with popping candy immediately before service.',
        ],
    ],
    [
        'flavour_key' => 'fig-honey',
        'sort_order' => 16,
        'name' => 'Fig & Honey',
        'tagline' => 'Technically, they’re on our side of the fence.',
        'story' => 'Our neighbour has a fig tree that leans over our fence. Every year, Dad and I grab as many ripe figs as we can and munch them before the birds get there. It feels slightly like stealing. It tastes considerably better.',
        'brief' => 'Ripe fig, floral honey and creamy mascarpone; soft, mellow and gently luxurious.',
        'ingredients' => [
            ['group' => null, 'qty' => '150g', 'item' => 'Figs'],
            ['group' => null, 'qty' => '70g', 'item' => 'Mascarpone'],
            ['group' => null, 'qty' => '15g', 'item' => 'Honey for roasting'],
            ['group' => null, 'qty' => '30g', 'item' => 'Runny honey'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '20g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '150g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '70g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '¼ tsp', 'item' => 'Salt'],
        ],
        'method' => [
            'Roast figs with 15g honey, lemon and salt at 180°C for about 20 minutes; cool and purée.',
            'Heat milk and cream with caster sugar, 30g honey and milk powder to about 82°C.',
            'Cool to about 55°C and blend in mascarpone and vanilla.',
            'Chill completely, then blend in roasted fig purée and salt.',
            'Mature cold and freeze/churn.',
            'Record fig intensity and texture.',
        ],
    ],
    [
        'flavour_key' => 'blood-orange',
        'sort_order' => 17,
        'name' => 'Blood Orange',
        'tagline' => 'The orange grin.',
        'story' => 'There are few things funnier than watching your children discover the orange grin. You know the one: wedge an orange segment in front of your teeth and grin like a complete lunatic. It never gets old. Ours adds a splash of Campari. That’s for the grown-ups.',
        'brief' => 'A clean blood-orange sorbet with adult Campari bitterness sitting behind the fruit.',
        'ingredients' => [
            ['group' => null, 'qty' => '300g', 'item' => 'Blood orange juice'],
            ['group' => null, 'qty' => '', 'item' => 'Zest of 1 blood orange'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '35g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '10g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '50g', 'item' => 'Water'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '1 tsp', 'item' => 'Campari'],
        ],
        'method' => [
            'Warm water with sugar, glucose and zest until dissolved; do not boil aggressively.',
            'Cool completely and strain if necessary.',
            'Blend in blood orange juice, lemon juice, Campari and salt.',
            'Chill thoroughly and rest before freezing.',
            'Freeze/churn to a smooth sorbet texture.',
            'Record firmness after 24 hours; alcohol can soften the finished sorbet.',
        ],
    ],
    [
        'flavour_key' => 'cherry-almond',
        'sort_order' => 18,
        'name' => 'Cherry & Almond',
        'tagline' => 'Cherries are showing off.',
        'story' => 'God made the earth, the sea, the stars, the sun, the animals and people. Then, apparently, he had a little bit of special magic left over. So he made cherries.',
        'brief' => 'Juicy cherry first, almond second. The almond should deepen the cherry rather than dominate it.',
        'ingredients' => [
            ['group' => null, 'qty' => '170g', 'item' => 'Cherries'],
            ['group' => null, 'qty' => '20g', 'item' => 'Caster sugar for fruit'],
            ['group' => null, 'qty' => '5g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '150g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '80g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '25g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '25g', 'item' => '100% almond butter'],
            ['group' => null, 'qty' => '¼ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '', 'item' => 'Flaked almonds, to finish'],
        ],
        'method' => [
            'Cook cherries with 20g sugar until softened; add lemon, purée and cool.',
            'Heat milk and cream with remaining sugar, glucose and milk powder to about 82°C.',
            'Blend in almond butter, vanilla and salt; chill completely.',
            'Blend in cherry purée until even.',
            'Mature cold and freeze/churn.',
            'Finish with toasted flaked almonds at service.',
        ],
    ],
    [
        'flavour_key' => 'chocolate-passionfruit',
        'sort_order' => 19,
        'name' => 'Chocolate & Passionfruit',
        'tagline' => 'Christmas, with a surprise.',
        'story' => 'Every Christmas I make a chocolate and passionfruit tart. Rich dark chocolate, sharp passionfruit and one slightly ridiculous secret ingredient: popping candy. This is the gelato version. Look out for the surprise.',
        'brief' => 'Dense dark chocolate cut sharply by passionfruit, with popping candy providing the final surprise.',
        'ingredients' => [
            ['group' => null, 'qty' => '130g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '5g', 'item' => 'Cocoa'],
            ['group' => null, 'qty' => '100g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '7', 'item' => 'Passionfruits (about 90g pulp)'],
            ['group' => null, 'qty' => '60g', 'item' => 'Shortbread'],
            ['group' => null, 'qty' => '65g', 'item' => '70% dark chocolate'],
            ['group' => null, 'qty' => '15g', 'item' => 'White chocolate'],
            ['group' => null, 'qty' => '30g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '12g', 'item' => 'Popping candy'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt for topping'],
            ['group' => null, 'qty' => '10g', 'item' => 'Skimmed milk powder'],
        ],
        'method' => [
            'Sieve passionfruit pulp and reserve the juice.',
            'Heat milk and cream with sugar, glucose, milk powder and cocoa to about 82°C.',
            'Pour over dark chocolate and blend smooth; chill completely.',
            'Blend in passionfruit juice and salt.',
            'Mature cold and freeze/churn.',
            'For service, combine shortbread, white chocolate and popping candy only shortly before use so the candy stays active.',
        ],
    ],
    [
        'flavour_key' => 'pistachio',
        'sort_order' => 20,
        'name' => 'Pistachio',
        'tagline' => 'The first shop of the holiday.',
        'story' => 'Whenever we go away, there are two things we buy before anything else: beer and pistachios. Unfortunately, I always forget the extra bowl for the shells. Which means that, sooner or later, I’ll absent-mindedly pick one up and try to eat it. You’d think I’d learn. I haven’t.',
        'brief' => 'Pure pistachio character with restrained sweetness, honey and salt used only to make the nut taste more itself.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '75g', 'item' => '100% pistachio paste'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '0.4g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '¼ tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => '', 'item' => 'Runny honey and sea salt flakes, to finish'],
        ],
        'method' => [
            'Combine sugar, milk powder and xanthan.',
            'Heat milk and cream; whisk in dry ingredients and heat to about 82°C.',
            'Blend in pistachio paste until completely emulsified.',
            'Add vanilla and fine salt; chill rapidly.',
            'Mature overnight and freeze/churn.',
            'Finish with a restrained drizzle of honey and a few sea-salt flakes.',
        ],
    ],
    [
        'flavour_key' => 'milk-chocolate',
        'sort_order' => 21,
        'name' => 'Milk Chocolate',
        'tagline' => 'A Curly Wurly when you need it.',
        'story' => 'My eldest daughter Nina really doesn’t like sweets, but she can eat chocolate all day long. Dark chocolate doesn’t quite cut it. Any Cadbury’s bar she can get hold of will make her life infinitely better. This milk chocolate is much more luxurious, but it still pays homage to a Curly Wurly whenever you need it.',
        'brief' => 'Luxurious, creamy and unmistakably milk-chocolate-led: softer and sweeter than Dark Chocolate, but with enough cocoa depth to avoid becoming cloying.',
        'ingredients' => [
            ['group' => null, 'qty' => '220g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '10g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '90g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '2', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '90g', 'item' => 'Milk chocolate'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '15g', 'item' => 'Cocoa powder'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
        ],
        'method' => [
            'Combine milk and cream and heat until steaming.',
            'Whisk yolks with caster sugar, cocoa, skimmed milk powder and xanthan.',
            'Temper the yolks with the hot dairy, return to the pan and cook gently to approximately 82°C.',
            'Pour the hot custard over the milk chocolate and glucose. Blend until completely smooth and emulsified.',
            'Add vanilla and salt. Chill rapidly, cover and mature overnight.',
            'Freeze/churn using the current Bean & Bear production method; record finished frozen weight and texture.',
        ],
    ],
    [
        'flavour_key' => 'cookies-cream',
        'sort_order' => 22,
        'name' => 'Cookies & Cream',
        'tagline' => 'The Oreo milkshake, frozen.',
        'story' => 'Sometimes we’ll go out for lunch, and if the girls are really well behaved, we might get them a milkshake. Their go-to milkshake is always an Oreo special. So this is a homage to an Oreo milkshake in an ice cream.',
        'brief' => 'Vanilla-forward, creamy and nostalgic, with biscuit flavour through the base and distinct cookie pieces for texture.',
        'ingredients' => [
            ['group' => null, 'qty' => '220g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '90g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '60g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '10g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '0.4g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '80g', 'item' => 'Chocolate sandwich biscuits — 30g for base, 50g for pieces'],
        ],
        'method' => [
            'Combine caster sugar, skimmed milk powder and xanthan thoroughly.',
            'Heat milk and cream; whisk in the dry ingredients and glucose and bring to approximately 82°C.',
            'Blend 30g of the sandwich biscuits into the hot base until smooth. Add vanilla and salt.',
            'Chill rapidly, cover and mature overnight.',
            'Freeze/churn using the current Bean & Bear production method.',
            'Fold through the remaining 50g biscuit pieces after freezing so distinct pieces remain. Record finished frozen weight and texture.',
        ],
    ],
    [
        'flavour_key' => 'honeycomb',
        'sort_order' => 23,
        'name' => 'Honeycomb',
        'tagline' => 'A very sticky kitchen.',
        'story' => 'The first time we ever made honeycomb was an absolute disaster. A three-year-old with a rolling pin smashing up golden syrup and bicarbonate of soda does not make for a happy kitchen, but it was a lot of fun nonetheless.',
        'brief' => 'Warm caramel and honeycomb flavour in a creamy base, with crisp shards added late enough to keep their crunch.',
        'ingredients' => [
            ['group' => null, 'qty' => '200g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '15g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '90g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '25g', 'item' => 'Light brown sugar'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '60g', 'item' => 'Honeycomb, broken into pieces'],
        ],
        'method' => [
            'Combine both sugars, skimmed milk powder and xanthan thoroughly.',
            'Heat milk and cream; whisk in the dry ingredients and glucose and bring to approximately 82°C.',
            'Add vanilla and salt. Chill rapidly, cover and mature overnight.',
            'Freeze/churn using the current Bean & Bear production method.',
            'Fold through roughly two-thirds of the honeycomb pieces after freezing. Keep the remainder dry for service.',
            'Record crunch after 24 hours as well as finished frozen weight and texture.',
        ],
    ],
    [
        'flavour_key' => 'rum-raisin',
        'sort_order' => 24,
        'name' => 'Rum & Raisin',
        'tagline' => 'Meg’s favourite.',
        'story' => 'Meg’s favourite. One for the adults. A delicious dash of dark rum, raisins soaked in the liquor, and a very creamy golden ice cream to top it all off.',
        'brief' => 'Rich, golden and grown-up: a custard-led gelato with plump rum-soaked raisins and enough dark rum to be unmistakable without overwhelming the dairy.',
        'ingredients' => [
            ['group' => null, 'qty' => '70g', 'item' => 'Raisins'],
            ['group' => null, 'qty' => '65g', 'item' => 'Light brown sugar'],
            ['group' => null, 'qty' => '35g', 'item' => 'Dark rum, plus soaking liquid'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '220g', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '10g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '100g', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '3', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
        ],
        'method' => [
            'Soak the raisins in the dark rum for at least 4 hours, preferably overnight. Drain before use, reserving the soaking liquid.',
            'Heat milk and cream until steaming. Whisk yolks with brown sugar and skimmed milk powder.',
            'Temper the yolks with the hot dairy, return to the pan and cook gently to 82–84°C.',
            'Add glucose, vanilla and salt. Chill rapidly, cover and mature overnight.',
            'Stir the reserved rum soaking liquid into the cold base, then freeze/churn using the current Bean & Bear production method.',
            'Fold through the drained raisins after freezing. Record softness after 24 hours because alcohol will affect the set.',
        ],
    ],
    [
        'flavour_key' => 'salted-caramel-popcorn',
        'sort_order' => 25,
        'name' => 'Salted Caramel Popcorn',
        'tagline' => 'The cinema isn’t the cinema without popcorn.',
        'story' => 'I love going to the cinema. For a couple of hours, the rest of life disappears. You sit on a sofa, put your arms around the people you love and watch something silly, funny, brilliant or occasionally absolutely terrible. None of that really matters, though, because the important bit is having an unnecessarily enormous bag of popcorn in front of you.',
        'brief' => 'Cinema popcorn made grown-up: toasted corn, dark caramel and salt, with enough savoury character to avoid simple sweetness.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '90ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '25g', 'item' => 'Freshly popped unsalted popcorn'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => 'Caramel', 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => 'Caramel', 'qty' => '15g', 'item' => 'Butter'],
            ['group' => 'Caramel', 'qty' => '25g', 'item' => 'Warm cream'],
            ['group' => 'Caramel', 'qty' => '1g', 'item' => 'Sea salt'],
        ],
        'method' => [
            'Toast the popcorn dry until deeply aromatic.',
            'Infuse it in steaming milk and cream for 30 minutes; blend briefly, sieve and top the liquid back up with milk to its original dairy weight.',
            'Add sugar, glucose, milk powder and xanthan and heat to about 82°C. Add vanilla and salt; chill and mature.',
            'Make a dark amber caramel; whisk in warm cream, then butter and salt. Cool.',
            'Freeze/churn the gelato and ripple the caramel through after freezing.',
            'Finish with crushed caramelised popcorn and sea salt. S A LT E D C A R A M E L P O P C O R N · M E T H O D                                                                    54',
        ],
    ],
    [
        'flavour_key' => 'kiwi-elderflower',
        'sort_order' => 26,
        'name' => 'Kiwi & Elderflower',
        'tagline' => 'Yes, I eat the skin.',
        'story' => 'I spent a few months picking kiwis in New Zealand. It was one of those periods of life that stays with you: beautiful country, wonderful people and extraordinary generosity. Meg mostly remembers that I came home thinking it was perfectly normal to eat kiwis with the skin on. Apparently it isn’t. Don’t worry. We took the skin off for this.',
        'brief' => 'Kiwi should stay vivid and tangy; elderflower adds fragrance and lift without turning the sorbet floral.',
        'ingredients' => [
            ['group' => null, 'qty' => '300g', 'item' => 'Ripe kiwi flesh'],
            ['group' => null, 'qty' => '20g', 'item' => 'Elderflower cordial'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '15g', 'item' => 'Lime juice'],
            ['group' => null, 'qty' => '30g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '45g', 'item' => 'Water'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Sea salt'],
        ],
        'method' => [
            'Warm water, sugar and glucose just enough to dissolve; cool completely.',
            'Blend in kiwi, elderflower, lime, xanthan and salt until smooth.',
            'Taste for acidity; only adjust lime in the next recorded version.',
            'Chill thoroughly.',
            'Freeze/churn as a sorbet.',
            'Serve without garnish initially so colour and flavour can be assessed cleanly.',
        ],
    ],
    [
        'flavour_key' => 'earl-grey-lemon',
        'sort_order' => 27,
        'name' => 'Earl Grey & Lemon',
        'tagline' => 'You can always tell when Mum’s been here.',
        'story' => 'My mum doesn’t take milk in her tea. So whenever she’s been to our house, there’s usually a used teabag, half a cup of tea and a slice of lemon abandoned somewhere in the kitchen. It’s a tiny bit of evidence that she’s been around. Earl Grey, lemon and the reassuring knowledge that Mum has probably left something by the sink.',
        'brief' => 'Tea first, bergamot and lemon second: clean, aromatic and refreshing rather than tannic.',
        'ingredients' => [
            ['group' => null, 'qty' => '220ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '90ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '6g', 'item' => 'Loose-leaf Earl Grey'],
            ['group' => null, 'qty' => '', 'item' => 'Zest of 1 lemon'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Salt'],
        ],
        'method' => [
            'Heat milk and cream to around 80°C; add tea and lemon zest.',
            'Cover and infuse for 8 minutes, then strain promptly.',
            'Add sugar, glucose, milk powder and xanthan and heat to about 82°C.',
            'Add vanilla and salt; chill rapidly.',
            'Mature overnight and freeze/churn.',
            'Assess bergamot, tannin and lemon balance before changing infusion time.',
        ],
    ],
    [
        'flavour_key' => 'white-chocolate-miso',
        'sort_order' => 28,
        'name' => 'White Chocolate & Miso',
        'tagline' => 'Sweet, with a little something unexpected.',
        'story' => 'My girls would happily eat their own body weight in white chocolate. Ridiculously sweet. Just like them. The miso is the little twist: salty, savoury and slightly unexpected. If our family is ordering a takeaway, there is a very good chance something Asian is arriving at the door. This is where those two worlds meet.',
        'brief' => 'Sweet white chocolate sharpened by savoury miso. The saltiness should create depth, not announce itself as miso soup.',
        'ingredients' => [
            ['group' => null, 'qty' => '210ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '12g', 'item' => 'White miso'],
            ['group' => null, 'qty' => '70g', 'item' => 'White chocolate'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '25g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla paste'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => 'Sesame brittle', 'qty' => '35g', 'item' => 'Sugar'],
            ['group' => 'Sesame brittle', 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => 'Sesame brittle', 'qty' => '15g', 'item' => 'Toasted sesame'],
        ],
        'method' => [
            'Heat milk and cream. Add sugar, milk powder, xanthan and glucose; heat to about 82°C.',
            'Pour over white chocolate and emulsify.',
            'Blend in miso and vanilla; chill rapidly and mature overnight.',
            'Make a thin sesame brittle from caramelised sugar, sesame and salt; cool and shatter.',
            'Freeze/churn the gelato.',
            'Finish with a small amount of sesame brittle.',
        ],
    ],
    [
        'flavour_key' => 'coffee-cardamom',
        'sort_order' => 29,
        'name' => 'Coffee & Cardamom',
        'tagline' => 'Meg has never learned to use the coffee machine.',
        'story' => 'Buying my first proper coffee machine made a material improvement to my quality of life. Curiously, Meg has managed to live alongside one for years without ever learning how to operate it. Which means that most mornings a cup of coffee somehow finds its way upstairs and arrives beside her in bed. Funny how that works.',
        'brief' => 'Proper coffee intensity with cardamom as an aromatic lift. Neither should obscure the other.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '50ml', 'item' => 'Strong espresso'],
            ['group' => null, 'qty' => '90ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '5', 'item' => 'Green cardamom pods'],
            ['group' => null, 'qty' => '60g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
        ],
        'method' => [
            'Lightly crush cardamom. Infuse in hot milk and cream for 15 minutes; strain.',
            'Add sugar, glucose, milk powder and xanthan; heat to about 82°C.',
            'Cool slightly, then add espresso and salt.',
            'Chill rapidly and mature overnight.',
            'Freeze/churn.',
            'Finish simply; optional coffee praline should be tested separately.',
        ],
    ],
    [
        'flavour_key' => 'brown-butter-sage',
        'sort_order' => 30,
        'name' => 'Brown Butter & Sage',
        'tagline' => 'We had to find something to do with all the sage.',
        'story' => 'We grow sage in the garden. Or, more accurately, sage grows in the garden and we occasionally attempt to contain it. Leave it alone for five minutes and it appears to be making plans for the rest of the flowerbed. So this flavour is partly delicious and partly a form of horticultural population control.',
        'brief' => 'Nutty brown butter leads; sage should feel fragrant and culinary, never medicinal.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '5', 'item' => 'Sage leaves'],
            ['group' => null, 'qty' => '45g', 'item' => 'Unsalted butter'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
        ],
        'method' => [
            'Brown the butter until the milk solids are hazelnut-coloured and aromatic.',
            'Add sage for about 30 seconds, remove from heat and infuse 5 minutes; discard sage.',
            'Heat milk and cream with sugar, glucose, milk powder and xanthan to about 82°C.',
            'Blend in 30g browned butter, vanilla and salt.',
            'Chill and mature overnight, then freeze/churn.',
            'Finish with brown-butter shortbread; use sage garnish sparingly.',
        ],
    ],
    [
        'flavour_key' => 'pear-tonka-bean',
        'sort_order' => 31,
        'name' => 'Pear & Tonka Bean',
        'tagline' => 'Niamh’s first bite.',
        'story' => 'The first food Niamh ever ate was a Conference pear. She was about six months old, sitting in my arms while I was eating one. Apparently waiting to be offered some was taking too long, because she suddenly leaned across and plunged her whole face straight into it. Niamh is our Bean. So this one belongs to her.',
        'brief' => 'Soft pear is the focus, with tonka used sparingly for warmth and perfume. Verify commercial tonka compliance before approval.',
        'ingredients' => [
            ['group' => null, 'qty' => '180g', 'item' => 'Ripe pear'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '150ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '¼', 'item' => 'Tonka bean, finely grated'],
            ['group' => null, 'qty' => '70ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '8g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Salt'],
        ],
        'method' => [
            'Peel and dice pear; roast at 190°C for about 20 minutes and purée.',
            'Heat dairy with sugar, glucose, milk powder, xanthan and a very small amount of grated tonka to about 82°C.',
            'Chill completely.',
            'Blend in pear purée, lemon and salt.',
            'Mature cold and freeze/churn.',
            'Development only: confirm regulatory suitability of tonka before any commercial sale.',
        ],
    ],
    [
        'flavour_key' => 'hazelnut-gianduja',
        'sort_order' => 32,
        'name' => 'Hazelnut & Gianduja',
        'tagline' => 'There is almost always hazelnut involved.',
        'story' => 'Hazelnut has somehow worked its way into my everyday life. Coffee? Hazelnut. Ice cream? A little hazelnut syrup. Chocolate? Even better with hazelnut. I could pretend there is a profound family story behind this one. There isn’t. I just really, really like hazelnuts.',
        'brief' => 'Roasted hazelnut should dominate, with gianduja adding chocolate depth and indulgence.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '15g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '70g', 'item' => '100% roasted hazelnut paste'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '50g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => 'Ripple', 'qty' => '50g', 'item' => 'Gianduja + 15g double cream'],
        ],
        'method' => [
            'Heat dairy. Add sugar, milk powder, xanthan and glucose; heat to about 82°C.',
            'Blend in hazelnut paste, vanilla and salt.',
            'Chill rapidly and mature overnight.',
            'Melt gianduja with cream and cool until fluid but not hot.',
            'Freeze/churn gelato and ripple gianduja through after freezing.',
            'Finish with toasted chopped hazelnuts.',
        ],
    ],
    [
        'flavour_key' => 'chai',
        'sort_order' => 33,
        'name' => 'Chai',
        'tagline' => 'The world’s largest tea cupboard. Probably.',
        'story' => 'Two of our closest friends have a tea cupboard containing what appears to be approximately 400 different teas. Somehow, they can open it, reach into the chaos and immediately find the exact one they’re looking for. This is our tribute to them. No teabag required. Just a whole collection of spices, tea and the hope that we’ve chosen the right one.',
        'brief' => 'A coherent cup of spiced tea in gelato form: tea, cardamom, cinnamon and ginger integrated rather than competing.',
        'ingredients' => [
            ['group' => null, 'qty' => '220ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '½', 'item' => 'Cinnamon stick'],
            ['group' => null, 'qty' => '90ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '3', 'item' => 'Thin slices ginger'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '2', 'item' => 'Cloves'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '2', 'item' => 'Black peppercorns'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '4g', 'item' => 'Assam tea'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => null, 'qty' => '4', 'item' => 'Green cardamom pods'],
        ],
        'method' => [
            'Lightly crush the spices and infuse in hot dairy for 5 minutes.',
            'Remove from heat, add Assam tea and infuse a further 4 minutes; strain.',
            'Top dairy back up with milk if necessary. Add sugar, glucose, milk powder and xanthan; heat to about 82°C.',
            'Add salt, chill rapidly and mature overnight.',
            'Freeze/churn.',
            'Assess tea/spice balance before adding any garnish.',
        ],
    ],
    [
        'flavour_key' => 'olive-oil-sea-salt',
        'sort_order' => 34,
        'name' => 'Olive Oil & Sea Salt',
        'tagline' => 'Basically health food.',
        'story' => 'When I can’t think of anything to cook, pasta with really good olive oil and sea salt feels remarkably close to a proper meal. So we took the same idea and made ice cream with beautiful extra virgin olive oil and sea salt instead. Olive oil is good for you. Therefore, by an extremely questionable piece of logic, this probably counts as health food.',
        'brief' => 'Excellent olive oil must be recognisable. Creamy, fruity and savoury, with salt sharpening the finish.',
        'ingredients' => [
            ['group' => null, 'qty' => '220ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '35g', 'item' => 'Fruity extra-virgin olive oil'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '1.2g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
        ],
        'method' => [
            'Heat dairy with sugar, glucose, milk powder and xanthan to about 82°C.',
            'Cool to around 50°C.',
            'Slowly blend in olive oil until completely emulsified.',
            'Add vanilla and salt; chill rapidly and mature overnight.',
            'Freeze/churn.',
            'Finish with a few drops of the same oil and two or three flakes of sea salt. O L I V E O I L & S E A S A LT · M E T H O D                                                    72',
        ],
    ],
    [
        'flavour_key' => 'black-sesame-honey',
        'sort_order' => 35,
        'name' => 'Black Sesame & Honey',
        'tagline' => 'Sweet. Savoury. Somewhere in between.',
        'story' => 'We love teriyaki in our house – chicken, salmon, anything really. This isn’t teriyaki ice cream, because even we have limits. But black sesame and honey have that same lovely tension between savoury, nutty, salty and sweet. Familiar flavours, just somewhere you weren’t necessarily expecting to find them.',
        'brief' => 'Deep roasted sesame, gentle honey sweetness and a savoury edge. Dark, nutty and balanced.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '55g', 'item' => 'Black sesame paste'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '35g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '30g', 'item' => 'Runny honey'],
        ],
        'method' => [
            'Heat dairy. Add sugar, milk powder and xanthan; heat to about 82°C.',
            'Blend in sesame paste, honey, vanilla and salt.',
            'Chill rapidly and mature overnight.',
            'Freeze/churn.',
            'Assess bitterness and sesame intensity cold.',
            'Finish with a restrained honey drizzle and toasted sesame.',
        ],
    ],
    [
        'flavour_key' => 'gooseberry-elderflower',
        'sort_order' => 36,
        'name' => 'Gooseberry & Elderflower',
        'tagline' => 'Long summers in Grandma’s garden.',
        'story' => 'Meg’s grandma had a gooseberry bush in her garden in Norfolk. Every summer they’d pick the fruit together and turn it into gooseberry fool or a tart. This one is a memory of those enormous childhood summers when the garden seemed to go on forever and there wasn’t really anywhere else you needed to be.',
        'brief' => 'Tart gooseberry remains central; elderflower softens and perfumes without masking its sharpness.',
        'ingredients' => [
            ['group' => null, 'qty' => '300g', 'item' => 'Gooseberries'],
            ['group' => null, 'qty' => '25g', 'item' => 'Elderflower cordial'],
            ['group' => null, 'qty' => '60g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '10g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '30g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '50g', 'item' => 'Water'],
            ['group' => null, 'qty' => 'pinch', 'item' => 'Salt'],
        ],
        'method' => [
            'Cook gooseberries with water, sugar and glucose for 5–8 minutes until burst.',
            'Blend thoroughly and sieve; cool completely.',
            'Blend in elderflower, lemon, xanthan and salt.',
            'Chill thoroughly.',
            'Freeze/churn as a sorbet.',
            'Keep elderflower secondary to the gooseberry.',
        ],
    ],
    [
        'flavour_key' => 'maple-pecan-bourbon',
        'sort_order' => 37,
        'name' => 'Maple, Pecan & Bourbon',
        'tagline' => 'Pancakes, but for grown-ups.',
        'story' => 'One of my favourite family mornings starts with pancakes or waffles. Everyone chips in, although somehow this generally results in me standing at the cooker while everybody else waits to be fed. And there is only one proper topping: maple syrup. So we added pecans, a little bourbon and turned the whole morning into an ice cream. Slightly more grown-up. Only slightly.',
        'brief' => 'Maple-led with toasted pecan and restrained bourbon warmth: breakfast nostalgia with an adult finish.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '15g', 'item' => 'Bourbon'],
            ['group' => null, 'qty' => '45g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '45g', 'item' => 'Pure maple syrup'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => 'Praline', 'qty' => '50g', 'item' => 'Pecans'],
            ['group' => 'Praline', 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => 'Praline', 'qty' => '30g', 'item' => 'Caster sugar'],
        ],
        'method' => [
            'Toast pecans at 170°C for about 8 minutes.',
            'Caramelise praline sugar, add pecans and salt, cool and chop.',
            'Heat dairy with sugar, maple syrup, milk powder and xanthan to about 82°C.',
            'Cool before adding bourbon, vanilla and salt; chill and mature.',
            'Freeze/churn and fold through pecan praline.',
            'Finish with toasted pecan and a restrained maple drizzle.',
        ],
    ],
    [
        'flavour_key' => 'rhubarb-custard',
        'sort_order' => 38,
        'name' => 'Rhubarb & Custard',
        'tagline' => 'A pound to spend. Choose wisely.',
        'story' => 'Every Sunday after church, Mum would give my sister and me a pound each and let us loose in the sweet shop. I’d emerge clutching a little brown paper bag filled with Black Jacks and rhubarb and custards. Looking back, a pound bought an extraordinary amount of happiness. This is my homage to that little paper bag.',
        'brief' => 'The flavour of the sweet: tangy rhubarb against rich vanilla custard, instantly recognisable and nostalgic.',
        'ingredients' => [
            ['group' => 'Custard', 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => 'Custard', 'qty' => '90ml', 'item' => 'Double cream'],
            ['group' => 'Custard', 'qty' => '3', 'item' => 'Egg yolks'],
            ['group' => 'Custard', 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => 'Custard', 'qty' => '10g', 'item' => 'Skimmed milk powder'],
            ['group' => 'Custard', 'qty' => '1 tsp', 'item' => 'Vanilla paste'],
            ['group' => 'Custard', 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => 'Rhubarb', 'qty' => '180g', 'item' => 'Rhubarb'],
            ['group' => 'Rhubarb', 'qty' => '35g', 'item' => 'Caster sugar'],
            ['group' => 'Rhubarb', 'qty' => '10g', 'item' => 'Lemon juice'],
            ['group' => 'Rhubarb', 'qty' => '', 'item' => 'Strip orange zest'],
        ],
        'method' => [
            'Roast rhubarb, sugar and orange zest at 180°C for about 20 minutes; remove zest, add lemon and partially blend.',
            'Heat dairy. Whisk yolks with sugar and milk powder; temper and cook to about 82°C.',
            'Add vanilla and salt; chill rapidly and mature overnight.',
            'Freeze/churn the custard gelato.',
            'Ripple cold roasted rhubarb through the frozen gelato.',
            'Record whether the ripple remains distinct after holding.',
        ],
    ],
    [
        'flavour_key' => 'banana-peanut-chocolate',
        'sort_order' => 39,
        'name' => 'Banana, Peanut & Chocolate',
        'tagline' => 'The breakfast of champions. Sort of.',
        'story' => 'At the weekend, when the girls are feeling particularly cheeky, they’ll ask for toast with Nutella and peanut butter. It must be one of the most calorific breakfasts known to humankind. Naturally, they absolutely love it. Banana, peanut and chocolate takes that same gloriously excessive idea and puts it into a scoop. Probably not for breakfast.',
        'brief' => 'Big, playful and indulgent: ripe banana, roasted peanut and dark chocolate with enough salt to keep it balanced.',
        'ingredients' => [
            ['group' => null, 'qty' => '160g', 'item' => 'Very ripe banana'],
            ['group' => null, 'qty' => '40g', 'item' => '100% peanut butter'],
            ['group' => null, 'qty' => '150ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '8g', 'item' => 'Lemon juice'],
            ['group' => null, 'qty' => '70ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '35g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '0.3g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => 'Stracciatella', 'qty' => '45g', 'item' => '70–80% dark chocolate + 5g neutral oil'],
        ],
        'method' => [
            'Roast unpeeled banana at 190°C until black-skinned and soft, about 20 minutes; cool and weigh flesh.',
            'Heat dairy with sugar, glucose, milk powder and xanthan to about 82°C.',
            'Blend in banana, peanut butter, lemon, vanilla and salt; chill and mature.',
            'Melt chocolate with oil.',
            'Freeze/churn gelato; drizzle chocolate in thinly while folding so it sets into shards.',
            'Finish with roasted salted peanut crumb.',
        ],
    ],
    [
        'flavour_key' => 'birthday-cake',
        'sort_order' => 40,
        'name' => 'Birthday Cake',
        'tagline' => 'The one day nobody’s counting.',
        'story' => 'Birthday cakes have become serious business in our house. We’ve made Disney characters, swimming cakes, gymnastics cakes, unicorns, Wallace & Gromit – you name it, we’ve probably covered it in icing. This flavour is designed to take you back to the one day of the year when nobody judges you for eating far too much cake.',
        'brief' => 'Celebratory vanilla and white chocolate with real cake pieces; joyful and sweet without tasting synthetic.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '35g', 'item' => 'White chocolate'],
            ['group' => null, 'qty' => '80ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '1½ tsp', 'item' => 'Vanilla bean paste'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => 'Cake', 'qty' => '50g', 'item' => 'Flour'],
            ['group' => 'Cake', 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => 'Cake', 'qty' => '30g', 'item' => 'Butter'],
            ['group' => 'Cake', 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => 'Cake', 'qty' => '25g', 'item' => 'Caster sugar'],
            ['group' => 'Cake', 'qty' => '10g', 'item' => 'Rainbow sprinkles'],
            ['group' => 'Cake', 'qty' => '1', 'item' => 'Egg yolk'],
        ],
        'method' => [
            'Cream cake butter and sugar; mix in yolk and vanilla, then flour, salt and sprinkles.',
            'Bake about 1cm thick at 170°C fan for 10–12 minutes; cool and crumble into small pieces.',
            'Heat dairy with sugar, glucose, milk powder and xanthan to about 82°C; pour over white chocolate and emulsify. Add vanilla and salt.',
            'Chill rapidly and mature overnight.',
            'Freeze/churn and fold through 50–60g cake pieces.',
            'Finish with a restrained scattering of sprinkles and cake crumb.',
        ],
    ],
    [
        'flavour_key' => 'chocolate-brownie',
        'sort_order' => 41,
        'name' => 'Chocolate Brownie',
        'tagline' => 'Absolutely no attempt to be sensible.',
        'story' => 'This one’s for the kids. Gooey, sticky, chocolatey and very, very naughty, all folded into one ice cream. There isn’t a clever story behind it and there doesn’t need to be. If chocolate is your thing, this is the one for you.',
        'brief' => 'Maximum chocolate comfort: dense cocoa, fudgy brownie and a little salt. Gooey and unapologetically rich.',
        'ingredients' => [
            ['group' => null, 'qty' => '200ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '60g', 'item' => '60–70% dark chocolate'],
            ['group' => null, 'qty' => '90ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '10g', 'item' => 'Cocoa powder'],
            ['group' => null, 'qty' => '3', 'item' => 'Egg yolks'],
            ['group' => null, 'qty' => '10g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '55g', 'item' => 'Caster sugar'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla'],
            ['group' => null, 'qty' => '15g', 'item' => 'Light brown sugar'],
            ['group' => null, 'qty' => '1g', 'item' => 'Sea salt'],
            ['group' => 'Brownie', 'qty' => '50g', 'item' => 'Dark chocolate'],
            ['group' => 'Brownie', 'qty' => '20g', 'item' => 'Flour'],
            ['group' => 'Brownie', 'qty' => '35g', 'item' => 'Butter'],
            ['group' => 'Brownie', 'qty' => '8g', 'item' => 'Cocoa'],
            ['group' => 'Brownie', 'qty' => '45g', 'item' => 'Light brown sugar'],
            ['group' => 'Brownie', 'qty' => 'pinch', 'item' => 'Salt'],
            ['group' => 'Brownie', 'qty' => '1', 'item' => 'Egg'],
        ],
        'method' => [
            'Melt brownie chocolate and butter. Whisk egg and sugar briefly; combine, then fold in flour, cocoa and salt.',
            'Bake at 170°C fan for 10–14 minutes so the centre remains fudgy; cool, chill and dice.',
            'Heat dairy. Whisk yolks with sugars, cocoa and milk powder; temper and cook to 82–84°C.',
            'Pour over chocolate and blend glossy; add vanilla and salt. Chill and mature.',
            'Freeze/churn and fold through 60–70g brownie pieces.',
            'Finish with brownie pieces and a tiny pinch of flaky salt.',
        ],
    ],
    [
        'flavour_key' => 'strawberry-cheesecake',
        'sort_order' => 42,
        'name' => 'Strawberry Cheesecake',
        'tagline' => 'What’s for pud?',
        'story' => 'After almost every meal when I was little, I’d ask the same question: ’What’s for pud?’ And one of the best answers was a shop-bought frozen strawberry cheesecake. There was absolutely nothing sophisticated about it, but it put an enormous smile on my face every time. Ours is rather more sophisticated. But hopefully, somewhere underneath all that proper strawberry and creamy cheesecake, there’s still a little taste of being a child and discovering what’s for pud.',
        'brief' => 'A homogeneous strawberry-cheesecake gelato: proper fruit, tangy cream cheese and crisp biscuit added only at service.',
        'ingredients' => [
            ['group' => null, 'qty' => '180g', 'item' => 'Ripe strawberries'],
            ['group' => null, 'qty' => '25g', 'item' => 'Caster sugar – fruit'],
            ['group' => null, 'qty' => '8g', 'item' => 'Fresh lemon juice'],
            ['group' => null, 'qty' => '150ml', 'item' => 'Whole milk'],
            ['group' => null, 'qty' => '65ml', 'item' => 'Double cream'],
            ['group' => null, 'qty' => '90g', 'item' => 'Full-fat cream cheese'],
            ['group' => null, 'qty' => '40g', 'item' => 'Caster sugar – base'],
            ['group' => null, 'qty' => '20g', 'item' => 'Glucose syrup'],
            ['group' => null, 'qty' => '15g', 'item' => 'Skimmed milk powder'],
            ['group' => null, 'qty' => '½ tsp', 'item' => 'Vanilla bean paste'],
            ['group' => null, 'qty' => '0.35g', 'item' => 'Xanthan gum'],
            ['group' => null, 'qty' => '1g', 'item' => 'Fine sea salt'],
            ['group' => null, 'qty' => '', 'item' => 'Digestive biscuit, crushed – service finish'],
        ],
        'method' => [
            'Cook the strawberries with 25g caster sugar for 8-10 minutes until concentrated. Add the lemon juice and blend completely smooth. Cool.',
            'Combine the 40g caster sugar, skimmed milk powder and xanthan. Heat the milk and cream, whisk in the dry ingredients and glucose, and bring to approximately 82 C.',
            'Cool the dairy base to 50-60 C. Blend in the cream cheese, vanilla and sea salt until completely smooth.',
            'Add the entire cooled strawberry preparation and blend again. The mix should be completely homogeneous and pale strawberry-pink.',
            'Chill thoroughly, cover and mature overnight. Freeze or churn using the current Bean & Bear production method.',
            'At service, finish with crushed digestive biscuit. Keep the biscuit out of the stored gelato so it remains dry and crisp. KIT CH E N N O T E S Notes NOTES                  89 KIT CH E N N O T E S Notes NOTES                  90 BEAN                    AND BEAR G E L AT O F L AV O U R S W I T H A S T O RY Beautiful gelato. Proper coffee. Stories worth sharing.',
        ],
    ],
];