<?php
declare(strict_types=1);

// Seed data: the distinct ingredient names used across the 42 recipes,
// used once, by db.php, to populate an empty ingredients table.
// Stock levels start at 0 -- there is no real stock data to seed from.
return [
    '100% almond butter',
    '100% peanut butter',
    '100% pistachio paste',
    '100% roasted hazelnut paste',
    '35–40g lime curd',
    '60–70% dark chocolate',
    '70% dark chocolate',
    '70–80% dark chocolate + 5g neutral oil',
    '80% dark chocolate',
    '80% dark chocolate with sea salt',
    'Assam tea',
    'Biscuit crumb or dulce de leche',
    'Black peppercorns',
    'Black sesame paste',
    'Blackcurrants',
    'Blood orange juice',
    'Bourbon',
    'Brown-butter shortbread',
    'Butter',
    'Campari',
    'Caster sugar',
    'Caster sugar for cherries',
    'Caster sugar for fruit',
    'Caster sugar total',
    'Cherries',
    'chocolate',
    'Chocolate sandwich biscuits — 30g for base, 50g for pieces',
    'Cinnamon stick',
    'Cloves',
    'Cocoa',
    'Cocoa powder',
    'Condensed milk',
    'Dark chocolate',
    'Dark chocolate shavings',
    'Dark rum',
    'Dark rum, plus soaking liquid',
    'Digestive biscuit',
    'Double cream',
    'Dulce de leche',
    'Egg',
    'Egg yolk',
    'Egg yolks',
    'Egg yolks — verify against original',
    'Elderflower cordial',
    'Espresso powder',
    'Figs',
    'Fine sea salt',
    'Flaked almonds',
    'Flour',
    'Freeze-dried strawberries',
    'Fresh lemon juice',
    'Freshly popped unsalted popcorn',
    'Fruity extra-virgin olive oil',
    'Full-fat cream cheese',
    'Gianduja + 15g double cream',
    'Glucose syrup',
    'Gooseberries',
    'Green cardamom pods',
    'Honey for roasting',
    'Honeycomb, broken into pieces',
    'Ladyfinger crumb and shaved',
    'Lemon juice',
    'Light brown sugar',
    'Lime juice',
    'Lime zest',
    'Liquorice powder',
    'Loose-leaf Earl Grey',
    'Mango pulp',
    'Mascarpone',
    'Meringue',
    'Meringue crumble and freeze-dried raspberry',
    'Milk chocolate',
    'Monin cherry syrup',
    'Monin coconut syrup',
    'Passionfruits (about 90g pulp)',
    'Peaches',
    'Pecans',
    'Pineapple',
    'Popping candy',
    'Pulp of 10 passionfruits',
    'Pure maple syrup',
    'Rainbow sprinkles',
    'Raisins',
    'Raspberries',
    'Rhubarb',
    'Ripe banana',
    'Ripe kiwi flesh',
    'Ripe pear',
    'Ripe strawberries',
    'Runny honey',
    'Runny honey and sea salt flakes',
    'Saffron strands',
    'Sage leaves',
    'Salt',
    'Sea salt',
    'Sea salt for topping',
    'Shortbread',
    'Shortbread crumb',
    'Shot espresso martini mix',
    'Sicilian lemon extract',
    'Skimmed milk powder',
    'Sour cherries',
    'Strip orange zest',
    'Strong espresso',
    'Sugar',
    'Thin slices ginger',
    'Toasted sesame',
    'Tonka bean, finely grated',
    'Unsalted butter',
    'Vanilla',
    'Vanilla bean paste',
    'Vanilla extract',
    'Vanilla paste',
    'Vanilla pod',
    'Very ripe banana',
    'Warm cream',
    'Water',
    'White chocolate',
    'White miso',
    'Whole milk',
    'Xanthan gum',
    'Zest of 1 blood orange',
    'Zest of 1 lemon',
    'Zest of 2 lemons',
    'Zest of 2 limes',
];